language: julia

os:
  - linux

julia:
  - 1.0
  - 1.2
  - nightly

notifications:
  email: false

after_success:
- julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder())'
